Word Embedding techniques using Embediing layer In keras

In [2]:
from tensorflow.keras.preprocessing.text import one_hot 

In [3]:
#sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'i am a good boy',
      'i am a good developer',
      'understand the meaning of the word ',
      'your video is awesome']


In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of the word ',
 'your video is awesome']

In [5]:
#Declaring the size of the vocabulary
voc_size=10000

One Hot Representation

In [6]:
one_hot_rep=[one_hot(words,voc_size) for words in sent]
print(one_hot_rep)

[[1073, 4140, 4656, 3472], [1073, 4140, 4656, 8647], [1073, 1775, 4656, 4723], [6115, 944, 3231, 3530, 7910], [6115, 944, 3231, 3530, 9670], [6390, 1073, 7852, 4656, 1073, 8491], [5475, 5693, 1876, 5878]]


Word Embedding Representation

In [9]:
from tensorflow.keras.layers import  Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [13]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1073 4140 4656 3472]
 [   0    0    0    0 1073 4140 4656 8647]
 [   0    0    0    0 1073 1775 4656 4723]
 [   0    0    0 6115  944 3231 3530 7910]
 [   0    0    0 6115  944 3231 3530 9670]
 [   0    0 6390 1073 7852 4656 1073 8491]
 [   0    0    0    0 5475 5693 1876 5878]]


In [14]:
dim=10

In [17]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [18]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [19]:
print(model.predict(embedded_docs))

[[[ 0.03520029 -0.02986902  0.01194481  0.00909305 -0.01592169
   -0.00036185  0.04913336  0.01185193 -0.03285583 -0.00451437]
  [ 0.03520029 -0.02986902  0.01194481  0.00909305 -0.01592169
   -0.00036185  0.04913336  0.01185193 -0.03285583 -0.00451437]
  [ 0.03520029 -0.02986902  0.01194481  0.00909305 -0.01592169
   -0.00036185  0.04913336  0.01185193 -0.03285583 -0.00451437]
  [ 0.03520029 -0.02986902  0.01194481  0.00909305 -0.01592169
   -0.00036185  0.04913336  0.01185193 -0.03285583 -0.00451437]
  [ 0.0238453  -0.03568239  0.02017898  0.02099941  0.03864923
   -0.00371986  0.0130298  -0.0323267  -0.02928185  0.0347482 ]
  [ 0.00385015  0.04543013 -0.04473921 -0.01825788 -0.01881738
    0.03324359  0.02135586 -0.03486037 -0.0417902   0.02063281]
  [-0.02959248  0.03757669  0.04105994  0.02572862  0.00792246
    0.00080379  0.04611291 -0.02308347  0.02501465 -0.03698323]
  [ 0.02742514 -0.04516344 -0.02712492  0.04028692 -0.04991789
    0.03367176 -0.00597209  0.01072543  0.047414

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 1073, 4140, 4656, 3472], dtype=int32)

In [21]:
print(model.predict(embedded_docs)[0])

[[ 0.03520029 -0.02986902  0.01194481  0.00909305 -0.01592169 -0.00036185
   0.04913336  0.01185193 -0.03285583 -0.00451437]
 [ 0.03520029 -0.02986902  0.01194481  0.00909305 -0.01592169 -0.00036185
   0.04913336  0.01185193 -0.03285583 -0.00451437]
 [ 0.03520029 -0.02986902  0.01194481  0.00909305 -0.01592169 -0.00036185
   0.04913336  0.01185193 -0.03285583 -0.00451437]
 [ 0.03520029 -0.02986902  0.01194481  0.00909305 -0.01592169 -0.00036185
   0.04913336  0.01185193 -0.03285583 -0.00451437]
 [ 0.0238453  -0.03568239  0.02017898  0.02099941  0.03864923 -0.00371986
   0.0130298  -0.0323267  -0.02928185  0.0347482 ]
 [ 0.00385015  0.04543013 -0.04473921 -0.01825788 -0.01881738  0.03324359
   0.02135586 -0.03486037 -0.0417902   0.02063281]
 [-0.02959248  0.03757669  0.04105994  0.02572862  0.00792246  0.00080379
   0.04611291 -0.02308347  0.02501465 -0.03698323]
 [ 0.02742514 -0.04516344 -0.02712492  0.04028692 -0.04991789  0.03367176
  -0.00597209  0.01072543  0.04741433  0.00917659]]